server:
  port: 8185
  servlet:
    context-path: /WorkJob
spring: 
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/work_job?characterEncoding=utf8&useSSL=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  profiles:
    active: dev
  devtools:
     restart:
      enabled: false
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html




      
      
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml


